### ISSUE TITLE
Make the step "extender" conditional and merge both tasks into one

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/catalog#13]
## TODO

Make the step "extender" conditional within the Task: `buildpacks-extension-phases` and merge the task `buildpacks-phases` with `buildpacks-extension-phases`

The image `paketobuildpacks/builder-ubi8-base:0.0.202` supports to be executed as bash script
```
apiVersion: tekton.dev/v1 # or tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-push-task-run
  namespace: demo
spec:
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: my-quarkus-hello-project-pvc
  params:
    - name: APP_IMAGE
      value: my-gitea-http.gitea.svc.cluster.local:3000/giteaadmin/quarkus-hello
    - name: CNB_PLATFORM_API
      value: "0.13"
    - name: CNB_LOG_LEVEL
      value: info
    - name: CNB_BUILDER_IMAGE
      value: paketobuildpacks/builder-ubi8-base:0.0.202
    - name: CNB_RUN_IMAGE
      value: paketobuildpacks/run-ubi8-base:0.0.111
    - name: CACHE_IMAGE
      value: ""
    - name: CNB_USER_ID
      value: 1002
    - name: CNB_GROUP_ID
      value: 1000
    - name: CNB_INSECURE_REGISTRIES
      value: my-gitea-http.gitea.svc.cluster.local:3000
  taskSpec:
    workspaces:
      - name: source
     env:
        - name: CNB_PLATFORM_API
          value: $(params.CNB_PLATFORM_API) 
    steps:
      - name: analyzer
        image: $(params.CNB_BUILDER_IMAGE)
        script: |
          #!/usr/bin/env bash
          
          /cnb/lifecycle/analyzer \
             -log-level=$(params.CNB_LOG_LEVEL) \
             -layers=/layers \
             -run-image=$(params.CNB_RUN_IMAGE) \
             -cache-image=$(params.CACHE_IMAGE) \
             -uid=$(params.CNB_USER_ID) \
             -gid=$(params.CNB_GROUP_ID) \
             -insecure-registry=$(params.CNB_INSECURE_REGISTRIES) \
             $(params.APP_IMAGE)
        volumeMounts:
            - name: layers-dir
              mountPath: /layers
    volumes:
      - name: layers-dir
        emptyDir: {}
```

**Good news** as `when` is supported in a Task: https://tekton.dev/docs/pipelines/stepactions/#controlling-step-execution-with-when-expressions since release: [0.62](https://github.com/tektoncd/pipeline/releases/tag/v0.62.0) and this [PR](: https://github.com/quarkiverse/quarkus-tekton/pull/38#pullrequestreview-2798237006) !

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-2
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  generateName: step-when-example
spec:
  workspaces:
    - name: custom
      persistentVolumeClaim:
        claimName: my-pvc-2
  taskSpec:
    description: |
            A simple task that shows how to use when determine if a step should be executed
    steps:
      - name: should-execute
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo "executed..."          
        when:
          - input: "$(workspaces.custom.bound)"
            operator: in
            values: [ "true" ]
      - name: should-skip
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo skipskipskip          
        when:
          - input: "$(workspaces.custom2.bound)"
            operator: in
            values: [ "true" ]
      - name: should-continue
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo blabalbaba          
      - name: produce-step
        image: alpine
        results:
          - name: result2
            type: string
        script: |
                    echo -n "foo" | tee $(step.results.result2.path)
      - name: run-based-on-step-results
        image: alpine
        script: |
                    echo "wooooooo"
        when:
          - input: "$(steps.produce-step.results.result2)"
            operator: in
            values: [ "bar" ]
    workspaces:
      - name: custom
   ```
