### ISSUE TITLE
Remove annotation from pipelineRun as this is a component annotation !

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/catalog#3]
## Issue

Remove the annotation `appstudio.openshift.io/pac-provision: request` from the pipelineRun as this is a component annotation !
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: 'https://github.com/ch007m/tekton-pac?rev={{revision}}'
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    appstudio.openshift.io/request: "configure-pac"
    appstudio.openshift.io/pac-provision: request
```
