### ISSUE TITLE
Convert the hard coded parameters into variables

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/catalog#5]
## Issue

The following parameters are hard coded within the template and should be converted into variables that we can substitute:

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: 'https://github.com/ch007m/tekton-pac?rev={{revision}}' # TOBECONVERTED
...
spec:
  params:
    - name: dockerfile
      value: https://raw.githubusercontent.com/devfile-samples/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged # TOBECONVERTED
```
