### ISSUE TITLE
Removing the reference of the Dockerfile as we dont use it

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/catalog#7]
## Todo

We should remove the following hard coded parameter as we dont use until now and dont know if it is used or should be used

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
spec:
  params:
...
    - name: dockerfile
      value: https://raw.githubusercontent.com/devfile-samples/devfile-sample-code-with-quarkus/main/src/main/docker/Dockerfile.jvm.staged
```
